config/routes.rb
P4::Application.routes.draw do
  resources :tasks
  resources :systems
  resources :components

  resources :entries do
	resources :comments
  end

  devise_for :users
  devise_for :admin
  
  namespace :admin do
	root :to => "admin#index"
  end

  match "/entries.rss" => "entries#rss"
  
  root :to => "entries#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :entry
end

app/models/component.rb
class Component < ActiveRecord::Base
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user
  
  acts_as_taggable
  acts_as_taggable_on :authors
  acts_as_taggable_on :tasks
  #acts_as_taggable_on :part_num
  acts_as_taggable_on :systems
  acts_as_taggable_on :comps
  
  #validates :author, 		:presence => true
  #validates :title, 		:presence => true
  #validates :summary, 		:presence => true,
	#						:length => { :minimum => 20, :maxiumum => 200 }
  #validates :citation, 		:presence => true
  #validates :participants, 	:presence => true
  #validates :size, 			:presence => true
  #validates :realism, 		:presence => true
  
  has_many :comments, :dependent => :destroy

end

app/models/system.rb
class System < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :entries
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    authenticate_admin! 
	
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter(:get_entry)
  
  def get_entry
	@entry = Entry.find(params[:entry_id])
  end

  
  # POST /experiments
  # POST /experiments.xml
  def create
    authenticate_user!
    @comment = @entry.comments.create(params[:comment])
	@comment.user_id = current_user
	@comment.save
	redirect_to entry_path(@entry)
  end

  
  # DELETE /experiments/1
  # DELETE /experiments/1.xml
  def destroy
    @comment = @entry.comments.find(params[:id])
    @comment.destroy
	redirect_to entry_path(@entry)
  end
  
end

app/controllers/components_controller.rb
class ComponentsController < ApplicationController
  
  # POST /experiments
  # POST /experiments.xml
  def create
    authenticate_admin!
    @component = Component.create(params[:component])
	@component.save
	redirect_to admin_session_path
  end

  
  # DELETE /experiments/1
  # DELETE /experiments/1.xml
  def destroy
    @component = Component.find(params[:id])
    @component.destroy
	redirect_to admin_session_path
  end
  
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def tag_cloud
	@tags = Entry.author_counts
  end
  
  # GET /entries
  # GET /entries.xml
  def index
    #@tags = Entry.author_counts
	@filter = params[:filter]
	@sort_by = params[:sort_by]
	
	if (@filter)
		@entries = Entry.tagged_with(params[:filter], :order => @sort_by)
	else
		@entries = Entry.find(:all, :order => @sort_by)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @entries }
	  format.rss { render :rss => @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.xml
  def show
    @entry = Entry.find(params[:id])
	@entry.viewed += 1
	@entry.update_attributes(params[:entry])
	
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @entry }
	  format.rss { render :rss => @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.xml
  def new
    authenticate_user! 
    @entry = Entry.new
	@systems = Array.new[System.find(:all).size]
	@components = Array.new[Component.find(:all).size]
	
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
	@systems = Array.new[System.find(:all).size]
	@components = Array.new[Component.find(:all).size]
  end

  # POST /entries
  # POST /entries.xml
  def create
    @entry = Entry.new(params[:entry])
	@entry.viewed = 0
	@entry.user_id = current_user
	
	@systems = params[:systems]
	@systems.each do |s|
		@entry.system_list.add(s)
	end	
	
	@components = params[:components]
	@components.each do |c|
		@entry.comp_list.add(c)
	end
	
    respond_to do |format|
      if @entry.save
        format.html { redirect_to(@entry, :notice => 'Entry was successfully created.') }
        format.xml  { render :xml => @entry, :status => :created, :location => @entry }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.xml
  def update
    @entry = Entry.find(params[:id])
	
	@entry.system_list = ""
	@systems = params[:systems]
	@systems.each do |s|
		@entry.system_list.add(s)
	end	
	
	@entry.comp_list = ""
	@components = params[:components]
	@components.each do |c|
		@entry.comp_list.add(c)
	end
	
    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to(@entry, :notice => 'Entry was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.xml
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to(entries_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  
  # POST /experiments
  # POST /experiments.xml
  def create
    authenticate_admin!
    @system = System.create(params[:system])
	@system.save
	redirect_to admin_session_path
  end

  
  # DELETE /experiments/1
  # DELETE /experiments/1.xml
  def destroy
    @system = System.find(params[:id])
    @system.destroy
	redirect_to admin_session_path
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  # POST /experiments
  # POST /experiments.xml
  def create
    authenticate_admin!
    @task = Task.create(params[:task])
	@task.save
	redirect_to admin_session_path
  end

  
  # DELETE /experiments/1
  # DELETE /experiments/1.xml
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
	redirect_to admin_session_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
	include ActsAsTaggableOn::TagsHelper
end

app/views/admin/index.html.erb
<h3>Components:</h3>
<ul><% Component.find(:all).each do |component| %>
	<li><%= component.tag %>
	<%= link_to 'Delete', component, 
				:confirm => 'Are you sure?',
				:method => :delete %></li>
	<% end %>
</ul>
  
<%= form_for(Component.new) do |f| %>
	<% f.error_messages %>

	<div class="field">
		<%= f.text_field :tag %>
	</div>
	<div class="actions">
		<%= f.submit "Add Component" %>
	</div>
<% end %> 

<h3>Systems:</h3>
<ul><% System.find(:all).each do |system| %>
	<li><%= system.tag %>
	<%= link_to 'Delete', system, 
				:confirm => 'Are you sure?',
				:method => :delete %></li>
	<% end %>
</ul>
  
<%= form_for(System.new) do |f| %>
	<% f.error_messages %>

	<div class="field">
		<%= f.text_field :tag %>
	</div>
	<div class="actions">
		<%= f.submit "Add System" %>
	</div>
<% end %> 

<h3>Tasks:</h3>
<ul><% Task.find(:all).each do |task| %>
	<li><%= task.tag %>
	<%= link_to 'Delete', task, 
				:confirm => 'Are you sure?',
				:method => :delete %></li>
	<% end %>
</ul>
  
<%= form_for(Task.new) do |f| %>
	<% f.error_messages %>

	<div class="field">
		<%= f.text_field :tag %>
	</div>
	<div class="actions">
		<%= f.submit "Add Task" %>
	</div>
<% end %> 

app/views/admin/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

app/views/comments/_comment.html.erb
<p>
	<%= comment.comment %><br>
	<% if User.find(comment.user_id) == current_user %>
		<small><i>Added by: YOU!, <%= comment.created_at %></i><br>
		<%= link_to 'Delete Comment', [comment.entry, comment], 
				:confirm => 'Are you sure?',
				:method => :delete %></small>
	<% else %>
		<small><i>Added by: <%= User.find(comment.user_id).email %>, <%= comment.created_at %></i></small>
	<% end %>
</p> 

app/views/comments/_form.html.erb
<%= form_for([@entry, @entry.comments.build]) do |f| %>
	<% f.error_messages %>

	<div class="field">
		<%= f.text_field :comment %>
	</div>
	<div class="actions">
		<%= f.submit "Add Comment" %>
	</div>
<% end %> 

app/views/entries/_form.html.erb
<%= form_for @entry do |f| %>
	<input type="hidden" name="systems[]"> 
	<input type="hidden" name="components[]"> 
	
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Paper Title" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label 'Paper URL' %><br />
    <%= f.text_field :paper_url %>
  </div>
  <div class="field">
    <%= f.label :authors %><small><i> Use full names and separate by commas. (ie. 'Doug Bowman, Cheryl Stinson')</i></small><br />
    <%= f.text_field :author_list %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.date_select :year %>
  </div>
  <div class="field">
    <%= f.label 'Full citation' %><br />
    <%= f.text_field :citation %>
  </div>
  <div class="field">
    <%= f.label :task %><br />
	<% Task.find(:all).each do |t| %>
		<%= f.radio_button :task_list, t.tag %><%= t.tag %><br>
	<% end %>
  </div>
  <div class="field">
    Environment - Characterize the scale of the environment used:<br>
	<%= f.radio_button :env_dim, "1" %>2.5D (3D environment where everything is on a ground plane or a terrain)<br>
	<%= f.radio_button :env_dim, "2" %>3D (the parts of the environment and the user's movements are in all three dimensions)<br>
	<%= f.radio_button :env_dim, "3" %>Not reported<br>
  </div>
  <div class="field">
    Environment - Characterize the scale of the environment used:<br>
	<%= f.radio_button :env_scale, "1" %>Small (0-10 meters on a side)<br>
	<%= f.radio_button :env_scale, "2" %>Medium (10-100 meters on a side)<br>
	<%= f.radio_button :env_scale, "3" %>Large (>100 meters on a side)<br>
	<%= f.radio_button :env_scale, "4" %>Not reported<br>
  </div>
  <div class="field">
    Environment - Characterize the visual realism of the environment used in this experiment:<br>
	<%= f.radio_button :env_density, "1" %>Low (sparse, mostly empty space)<br>
	<%= f.radio_button :env_density, "2" %>Medium<br>
	<%= f.radio_button :env_density, "3" %>High (dense, little empty space)<br>
	<%= f.radio_button :env_density, "4" %>Not reported<br>
  </div>
  <div class="field">
    Environment - Characterize the visual realism of the environment used in this experiment:<br>
	<%= f.radio_button :env_realism, "1" %>Low (abstract, cartoony, simple)<br>
	<%= f.radio_button :env_realism, "2" %>Medium<br>
	<%= f.radio_button :env_realism, "3" %>High (looks highly realistic)<br>
	<%= f.radio_button :env_realism, "4" %>Not reported<br>
  </div>
  <div class="field">
	Participants - Gender balance of participants in this experiment:<br>
	<%= f.radio_button :part_num, "1" %>1-5<br>
	<%= f.radio_button :part_num, "2" %>6-10<br>
	<%= f.radio_button :part_num, "3" %>11-20<br>
	<%= f.radio_button :part_num, "4" %>21-50<br>
	<%= f.radio_button :part_num, "5" %>50+<br>
	<%= f.radio_button :part_num, "6" %>None<br>
  </div>
  <div class="field">
    Environment - Characterize the visual realism of the environment used in this experiment:<br>
	<%= f.radio_button :exp_type, "1" %>Controlled Experiment<br>
	<%= f.radio_button :exp_type, "2" %>Practical Comparison<br>
  </div>
  <div class="field">
	Systems Used:<br />
	<% System.find(:all).each do |s| %>
		<% if @entry.tag_list_on(:systems).include?(s.tag) %>
			<%= check_box_tag "systems[]", s.tag, true %><%= s.tag %><br>
		<% else %>
			<%= check_box_tag "systems[]", s.tag, false %><%= s.tag %><br>
		<% end %>
	<% end %>
  </div>
  <div class="field">
    Components of Immersion:<br />
	<% Component.find(:all).each do |c| %>
		<% if @entry.tag_list_on(:comps).include?(c.tag) %>
			<%= check_box_tag "components[]", c.tag, true %><%= c.tag %><br>
		<% else %>
			<%= check_box_tag "components[]", c.tag, false %><%= c.tag %><br>
		<% end %>
	<% end %>
  </div>
  <div class="field">
    <%= f.label :findings %><br />
    <%= f.text_area :findings %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<%= auto_discovery_link_tag(:rss, entries_url(:filter => @filter, :sort_by => @sort_by, :format => 'rss')) %>

<p>
	<b>Sort by: </b>
	<%= link_to 'Title', entries_path(:sort_by => "title ASC", :filter => @filter) %> | 
	<%= link_to 'Date', entries_path(:sort_by => "year DESC", :filter => @filter) %> | 
	<%= link_to 'Times Viewed', entries_path(:sort_by => "viewed DESC", :filter => @filter) %>
</p>

<% @entries.each do |entry| %>
<p>
	<big><b><%= link_to entry.title, entry %></b></big> - <%= entry.year %><br>
	<%= entry.author_list %><br>
	
	<% if entry.exp_type == 1 %>Controlled Experiment
	<% else %>Practical comparison
	<% end %><br>
	
	Tags: <%= entry.task_list %>, <%= entry.system_list %>, <%= entry.comp_list %><br>
	Times Viewed: <%= entry.viewed %><br>
		<%= link_to 'Edit', edit_entry_path(entry) %>
		<%= link_to 'Destroy', entry, :confirm => 'Are you sure?', :method => :delete %><br>

</p>
<% end %>

<br />

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<% @systems = Array.new %>
<% @components = Array.new %>
<%= render 'form', :locals => { @systems => @systems, @components => @components } %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<%= auto_discovery_link_tag(:rss, entry_url(@entry, :format => 'rss')) %>

<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @entry.title %>
</p>

<p>
  <b>Paper url:</b>
  <%= @entry.paper_url %>
</p>

<p>
  <b>Authors:</b>
  <%= @entry.author_list %>
</p>

<p>
  <b>Year:</b>
  <%= @entry.year %>
</p>

<p>
  <b>Citation:</b>
  <%= @entry.citation %>
</p>

<p>
  <b>Task:</b>
  <%= @entry.task_list %>
</p>

<p>
  <b>Env dim:</b>
  <%= @entry.env_dim %>
</p>

<p>
  <b>Env scale:</b>
  <%= @entry.env_scale %>
</p>

<p>
  <b>Env density:</b>
  <%= @entry.env_density %>
</p>

<p>
  <b>Env realism:</b>
  <%= @entry.env_realism %>
</p>

<p>
  <b>Part num:</b>
  <%= @entry.part_num %>
</p>

<p>
  <b>Exp type:</b>
  <%= @entry.exp_type %>
</p>

<p>
  <b>Systems:</b>
  <%= @entry.system_list %>
</p>

<p>
  <b>Comps:</b>
  <%= @entry.comp_list %>
</p>

<p>
  <b>Findings:</b>
  <%= @entry.findings %>
</p>

<p>
  <b>Summary:</b>
  <%= @entry.summary %>
</p>

<p>
  <b>Viewed:</b>
  <%= @entry.viewed %>
</p>

<ul><li><h3>Comments:</h3>
  <%= render :partial => "comments/comment", :collection => @entry.comments %> 

  <%= render "comments/form" %>
</li></ul>


<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project4</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path %>
  <% elsif admin_signed_in? %>
	Signed in as <%= current_admin.email %>. Not you?
    <%= link_to "Sign out", destroy_admin_session_path %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
	 | <%= link_to "Admin sign-in", new_admin_session_path %>
  <% end %>
</div>
<div id="container">
	<div id="header">
		<h1>
			VR Knowledgebase
		</h1>
	</div>
	<div id="navigation">
		<ul>

		</ul>
	</div>
	<div id="content-container">
		<div id="aside">

			<p>
				<h3>Components of Immersion:</h3>
				<% Component.find(:all).each do |c| %>
					<%= link_to c.tag, entries_path(:filter => c.tag) %> (<%= Entry.tagged_with(c.tag).size %>)<br>
				<% end %>
			</p>
			<p>
				<h3>Tasks:</h3>
				<% Task.find(:all).each do |t| %>
					<%= link_to t.tag, entries_path(:filter => t.tag) %> (<%= Entry.tagged_with(t.tag).size %>)<br>
				<% end %>
			</p>
			<p>
				<h3>Systems:</h3>
				<% System.find(:all).each do |s| %>
					<%= link_to s.tag, entries_path(:filter => s.tag) %> (<%= Entry.tagged_with(s.tag).size %>)<br>
				<% end %>
			</p>
		</div>
		<div id="content">
			<p>
				<%= yield %>
			</p>
		</div>

	</div>
		<div id="footer">
			Copyright
		</div>
</div>

</body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>